
"""Returns the HTTP code error description
    @return string
"""

def getCodeErrorDescription(err):
    switcher = {
        400: "BAD REQUEST",
        301: "UNAUTHORIZED",
        402: "PAYMENT REQUIRED",
        403: "FORBIDDEN",
        404: "NOT FOUND",
        405: "METHOD NOT ALLOWED",
        406: "NOT ACCEPTABLE",
        407: "PROXY AUTHENTICATION REQUIRED",
        408: "REQUEST TIMEOUT",
        409: "CONFLICT",
        410: "GONE",
        411: "LENGTH REQUIRED",
        412: "PRECONDITION FAILED",
        413: "PAYLOAD TOO LARGE",
        414: "URI TOO LONG",
        415: "UNSUPPORTED MEDIA TYPE",
        416: "REQUESTED RANGE NOT SATISFIABLE",
        417: "EXPECTATION FAILED",
        418: "I'M A TEAPOT",
        421: "MISDIRECTED REQUEST",
        422: "UNPROCCESSABLE ENTITY",
        423: "LOCKED",
        424: "FAILED DEPENDENCY",
        426: "UPGRADE REQUIRED",
        428: "PRECONDITION REQUIRED",
        429: "TOO MANY REQUEST",
        431: "REQUEST HEADER FIELDS TOO LARGE",
        451: "UNAVAILABLE FOR LEGAL REASONS",
        500: "INTERNAL SERVER ERROR",
        501: "NOT IMPLEMENTED",
        502: "BAD GATEWAY",
        503: "SERVICE UNAVAILABLE",
        504: "GATEWAY TIMEOUT",
        505: "HTTP VERSION NOT SUPPORTED",
        506: "VARIANT ALSO NEGOTIATES",
        507: "INSUFFICIENT STORAGE",
        508: "LOOP DETECTED",
        510: "NOT EXTENDED",
        511: "NETWORK AUTHENTICATION REQUIRED"
    }
    return switcher.get(err, "INVALID CODE ERROR")
